name: Atualizar Leaderboard

on:
  schedule:
    - cron: '0 15 * * *'
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5

      - name: Instalar dependências
        run: pip install pyyaml requests

      - name: Gerar leaderboard
        env:
          OR_KEY: ${{ secrets.OR_KEY }}
        run: python scripts/generate_leaderboard.py

      - name: Commit e Push das alterações
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/leaderboard.yml
          git commit -m "chore: atualiza leaderboard [skip ci]" || echo "Nenhuma alteração encontrada"
          git push
